---
title: Sense HAT Pong
hero_image: images/banner.png
description: 'In this activity you will make a single player Pong game using your
  Raspberry Pi and the Sense HAT. '
original_url: https://raspberrypi.org/learning/sense-hat-pong
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ''
technologies: rpi, physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Connect to the Sense HAT
- title: Graphics and coordinates
- title: Lighting up an LED
- title: Making a bat
- title: Moving the bat
- title: Creating a ball
- title: Moving the ball
- title: Collision with the bat
- title: What next?
