title: Sense HAT Pong
hero_image: images/banner.png
description: Make a single-player Pong game using your Raspberry Pi and Sense HAT
original_url: https://raspberrypi.org/learning/sense-hat-pong
theme: blue
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: games
technologies: physical computing, python
site_areas: ''
steps:
- title: Introduction
- title: What you will need
- title: Connect to the Sense HAT
- title: Light up an LED
- title: Make a bat
- title: Move the bat
- title: Create a ball
- title: Move the ball
- title: Collision with the bat
- title: You lose
- title: "Challenge: add more features"
